### PR TITLE
Feat/backend pull channel meta

### PR DESCRIPTION
**Pull request by ash626**
Changed pullData to twitchAPIHelpers, figured we can put all functions that interact with the twitch api here

Changed return of the functions from request objects to promises because promises have more support and are easier to use.

Added get channel meta-data function. technically its a get user meta-data function but for twitch the user is the channel

### CODE REVIEW

**Comment by ivankching** [comment]
I should have mentioned this in a previous PR, but what do you think about moving the file to a external/twitch directory, since the functions are making requests to a server outside of the application.

**Comment by ash626** [comment]
Sounds good, how about now?

**Comment by ivankching** [comment]
Could you make the functions async?

**Comment by ash626** [comment]
Was about to then saw that the request package was depreciated today..... I'll rework the file using a new package and async then chuck the PR back up

**Pull request merged**
